import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { ItemLine } from "@/types/procurement-records";
import { bdt, newItem } from "./procurement-options";
import { Field } from "./procurement-ui";

export function ItemEditor({ items, onChange }: { items: ItemLine[]; onChange: (items: ItemLine[]) => void }) {
  function update(index: number, patch: Partial<ItemLine>) { onChange(items.map((item, i) => i === index ? { ...item, ...patch } : item)); }
  return <div className="space-y-4">{items.map((item, index) => <fieldset key={index} className="rounded-xl border bg-background/50 p-4"><legend className="px-2 text-xs font-semibold text-primary">Item {index + 1}</legend><div className="grid gap-4 sm:grid-cols-2"><Field title="Item / service"><Input required maxLength={200} value={item.name} onChange={(e) => update(index, { name: e.target.value })} /></Field><Field title="Specification"><Input required maxLength={2000} value={item.specification} onChange={(e) => update(index, { specification: e.target.value })} /></Field></div><div className="mt-4 grid grid-cols-2 items-end gap-4 sm:grid-cols-4"><Field title="Quantity"><Input required type="number" min="0.01" max="100000" step="0.01" value={item.quantity} onChange={(e) => update(index, { quantity: e.target.valueAsNumber || 0 })} /></Field><Field title="Unit"><Input required maxLength={30} value={item.unit} onChange={(e) => update(index, { unit: e.target.value })} /></Field><Field title="Unit cost (BDT)"><Input required type="number" min="0" max="100000000" step="0.01" value={item.unit_cost} onChange={(e) => update(index, { unit_cost: e.target.valueAsNumber || 0 })} /></Field><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">{bdt(item.quantity * item.unit_cost)}</span><Button type="button" variant="ghost" size="icon" aria-label={`Remove item ${index + 1}`} disabled={items.length === 1} onClick={() => onChange(items.filter((_, i) => i !== index))}><Trash2 className="size-4" /></Button></div></div></fieldset>)}<div className="flex flex-wrap items-center justify-between gap-3"><Button type="button" variant="outline" disabled={items.length >= 50} onClick={() => onChange([...items, newItem()])}><Plus className="size-4" />Add item</Button><p className="font-semibold text-primary">Estimated total: {bdt(items.reduce((sum, item) => sum + item.quantity * item.unit_cost, 0))}</p></div></div>;
}
