import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { tenderApi, vendorApi } from "@/services/procurement";
import { StatusBadge } from "@/components/status-badge";
import { EmptyState } from "@/components/empty-state";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ActionHistory, ItemSummary, PageHeading, Panel, QueryState } from "@/features/procurement/procurement-ui";
import { date, label } from "@/features/procurement/procurement-options";
import { TenderGovernance } from "./tender-governance";

export function TenderDetailPage() {
  const { id = "" } = useParams();
  const query = useQuery({ queryKey: ["tenders", id], queryFn: ({ signal }) => tenderApi.get(id, signal) });
  const vendors = useQuery({ queryKey: ["vendors"], queryFn: ({ signal }) => vendorApi.list(signal) });
  if (query.isPending || query.isError) return <QueryState pending={query.isPending} error={query.error} retry={() => void query.refetch()} />;
  const tender = query.data; const selectedVendors = vendors.data?.filter((v) => tender.type === "public_tender" ? v.status === "approved" : (tender.invited_vendor_ids ?? []).includes(v.id));
  const closingTime = tender.closing_date ? new Date(tender.closing_date).toLocaleTimeString("en-GB", { timeZone: "Asia/Dhaka", hour: "2-digit", minute: "2-digit" }) : "";
  return <div className="space-y-6"><PageHeading title={tender.title} description={tender.tender_number} back="/admin/tenders" action={<StatusBadge status={tender.status} />} /><TenderGovernance tender={tender} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Tender type", label(tender.type)], ["Category", label(tender.category)], ["Closing deadline", `${date(tender.closing_date)} ${closingTime}`], ["Recorded bids", String(tender.bid_count)]].map(([title, value]) => <Panel key={title} title={title}><p className="font-semibold text-primary">{value}</p>{title === "Closing deadline" && <p className="text-xs text-muted-foreground">Dhaka time (UTC+6)</p>}</Panel>)}</div>
    <Tabs defaultValue="overview"><div className="overflow-x-auto pb-2"><TabsList>{["overview", "boq", "vendors", "documents", "clarifications", "addenda", "bids", "evaluation"].map((tab) => <TabsTrigger key={tab} value={tab}>{tab === "boq" ? "BOQ" : label(tab)}</TabsTrigger>)}</TabsList></div>
      <TabsContent value="overview"><div className="grid gap-5 xl:grid-cols-3"><div className="space-y-5 xl:col-span-2"><Panel title="Scope of supply / service"><p className="whitespace-pre-wrap leading-relaxed text-muted-foreground">{tender.scope || "Complete the scope before submitting this tender for approval."}</p><p className="text-sm">Source: {tender.requisition_id ? <Link to={`/admin/requisitions/${tender.requisition_id}`} className="font-medium text-primary hover:underline">Open linked requisition</Link> : "Independent tender"}</p></Panel><Panel title="Eligibility requirements"><p className="whitespace-pre-wrap leading-relaxed text-muted-foreground">{tender.eligibility || "Complete supplier eligibility in Edit tender before submission."}</p><Badge variant="secondary">{tender.type === "invited_tender" ? "Approved invited vendors only" : "Eligibility reviewed by hospital procurement"}</Badge></Panel></div><Panel title="Publication & governance"><p className="rounded-lg bg-secondary p-3 text-xs leading-relaxed text-muted-foreground">Draft → Pending Approval → Approved → Published. Tender notices and deadline changes are recorded below.</p><ActionHistory entries={tender.history} /></Panel></div></TabsContent>
      <TabsContent value="boq"><Panel title="Bill of quantities"><p className="text-xs text-muted-foreground">Estimated costs in BDT; these are not vendor bid prices.</p><ItemSummary items={tender.boq} /></Panel></TabsContent>
      <TabsContent value="vendors"><Panel title={tender.type === "public_tender" ? "Approved supplier reference list" : "Invited vendors"}><p className="text-xs text-muted-foreground">{tender.type === "public_tender" ? "Reference list only; no invitation or bid submission is implied." : "Selected suppliers for this sourcing exercise. Invitations are represented in the demo; no email is sent."}</p>{vendors.isPending || vendors.isError ? <QueryState pending={vendors.isPending} error={vendors.error} retry={() => void vendors.refetch()} /> : !selectedVendors?.length ? <EmptyState title="No vendors listed" description="Select approved vendors while editing an invited tender." /> : <ul className="divide-y">{selectedVendors.map((v) => <li key={v.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><Link to={`/admin/vendors/${v.id}`} className="font-medium text-primary hover:underline">{v.name}</Link><StatusBadge status={v.status} /></li>)}</ul>}</Panel></TabsContent>
      <TabsContent value="documents"><Panel title="Supporting documents">{!tender.documents?.length ? <EmptyState title="No document titles recorded" /> : <ul className="space-y-3">{tender.documents.map((document, index) => <li key={`${document}-${index}`} className="rounded-lg border p-4"><p className="font-medium">{document}</p><p className="mt-1 text-xs text-muted-foreground">Document register entry · Demo metadata</p></li>)}</ul>}<p className="text-xs text-muted-foreground">Original files are not attached in this demo register.</p></Panel></TabsContent>
      <TabsContent value="clarifications"><Panel title="Clarifications"><ActionHistory entries={tender.clarifications} /></Panel></TabsContent><TabsContent value="addenda"><Panel title="Published addenda"><ActionHistory entries={tender.addenda} /></Panel></TabsContent>
      <TabsContent value="bids"><Panel title="Bid overview"><p className="text-3xl font-semibold text-primary">{tender.bid_count}</p><p className="text-sm text-muted-foreground">Recorded bid count. Online submission and bid review are reserved for the bidding phase.</p></Panel></TabsContent><TabsContent value="evaluation"><Panel title="Evaluation overview"><StatusBadge status={tender.status} /><p className="text-sm text-muted-foreground">Scoring, comparison, and award recommendations will be available in the evaluation phase.</p></Panel></TabsContent>
    </Tabs>
  </div>;
}
