import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import { toast } from "sonner";
import { Building2, ShieldCheck, Star } from "lucide-react";
import { vendorApi } from "@/services/procurement";
import { useAuth } from "@/features/auth/use-auth";
import { StatusBadge } from "@/components/status-badge";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/empty-state";
import { ActionDialog, ActionHistory, PageHeading, Panel, QueryState } from "@/features/procurement/procurement-ui";
import { date, label } from "@/features/procurement/procurement-options";

export function VendorDetailPage() {
  const { id = "" } = useParams(); const { user } = useAuth(); const cache = useQueryClient();
  const query = useQuery({ queryKey: ["vendors", id], queryFn: ({ signal }) => vendorApi.get(id, signal) });
  const action = useMutation({ mutationFn: ({ name, note }: { name: string; note: string }) => vendorApi.action(Number(id), name, note), onSuccess: async () => { await Promise.all([cache.invalidateQueries({ queryKey: ["vendors"] }), cache.invalidateQueries({ queryKey: ["dashboard"] })]); toast.success("Vendor record updated."); } });
  if (query.isPending || query.isError) return <QueryState pending={query.isPending} error={query.error} retry={() => void query.refetch()} />;
  const vendor = query.data; const profile = vendor.profile; const act = (name: string) => async (note: string) => { await action.mutateAsync({ name, note }); };
  return <div className="space-y-6"><PageHeading title={vendor.name} description="Hospital supplier profile and lifecycle controls" back="/admin/vendors" action={<StatusBadge status={vendor.status} />} />
    {user?.role === "admin" && <div className="flex flex-wrap gap-2">{vendor.status !== "blacklisted" && !profile?.verified && <ActionDialog title="Verify compliance (demo)" description="Record a simulated tax and banking check. No external verification service is contacted." pending={action.isPending} onConfirm={act("verify")} />}{["pending_verification", "suspended"].includes(vendor.status) && <ActionDialog title="Approve vendor" description="Approve this supplier for hospital procurement. Simulated compliance verification must be complete." pending={action.isPending} onConfirm={act("approve")} />}{vendor.status === "approved" && <ActionDialog title="Suspend vendor" description="Temporarily suspend supplier eligibility and record the reason." needsNote destructive pending={action.isPending} onConfirm={act("suspend")} />}{vendor.status !== "blacklisted" && <ActionDialog title="Blacklist vendor" description="Restrict this supplier from procurement and record the reason." needsNote destructive pending={action.isPending} onConfirm={act("blacklist")} />}</div>}
    {vendor.document_expiry_alert && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Document attention required</strong><p className="mt-1">{vendor.document_expiry_alert}</p></div>}
    <div className="grid gap-5 xl:grid-cols-3"><div className="space-y-5 xl:col-span-2"><Panel title="Company"><div className="flex gap-4"><Building2 className="size-10 rounded-lg bg-secondary p-2 text-primary" /><div><p className="font-semibold">{vendor.name}</p><p className="mt-1 text-sm text-muted-foreground">{profile?.address ?? "No address recorded"}</p></div></div><div className="grid gap-3 text-sm sm:grid-cols-2"><p>Contact: {profile?.contact ?? "Not recorded"}</p><p>Phone: {profile?.phone ?? "Not recorded"}</p><p className="break-all">Email: {profile?.email ?? "Not recorded"}</p></div></Panel><div className="grid gap-5 sm:grid-cols-2"><Panel title="Registration"><p>{profile?.registration ?? "Not recorded"}</p><p className="text-xs text-muted-foreground">Sample trade registration reference</p></Panel><Panel title="Tax"><p>{profile?.tax ?? "Not recorded"}</p><Badge variant="outline">{profile?.verified ? "Tax Verified · Simulated" : "Tax verification pending"}</Badge></Panel></div><Panel title="Banking"><p>{profile?.bank ?? "Not recorded"}</p><p className="font-mono text-sm">Account: {profile?.account ?? "Not recorded"}</p><Badge variant="outline">{profile?.verified ? "Banking Verified · Simulated" : "Banking verification pending"}</Badge><p className="text-xs text-muted-foreground">Sample compliance information for the demonstration. No bank or tax authority connection.</p></Panel><Panel title="Documents">{!profile?.documents.length ? <EmptyState title="No documents recorded" /> : <ul className="divide-y">{profile.documents.map((doc) => <li key={doc.name} className="flex flex-wrap justify-between gap-3 py-3"><div><p className="font-medium">{doc.name}</p><p className="mt-1 text-xs text-muted-foreground">{doc.status}</p></div><span className="text-xs text-muted-foreground">{doc.expiry ? `Expires ${date(doc.expiry)}` : "No expiry recorded"}</span></li>)}</ul>}<p className="text-xs text-muted-foreground">Document register contains sample metadata; no original files are attached.</p></Panel></div><div className="space-y-5"><Panel title="Performance"><Star className="size-6 text-amber-600" /><p className="text-3xl font-semibold">{vendor.performance_score ?? "—"}<span className="ml-2 text-sm text-muted-foreground">/ 5</span></p><p className="text-xs text-muted-foreground">{vendor.performance_score ? "Seeded supplier performance score" : "No performance assessment recorded"}</p></Panel><Panel title="Categories"><Badge variant="secondary">{label(vendor.category)}</Badge></Panel><Panel title="Compliance"><p className="flex items-center gap-2 text-sm"><ShieldCheck className="size-4 text-primary" />{profile?.verified ? "Demo checks complete" : "Verification required"}</p><p className="text-xs text-muted-foreground">Lifecycle approval does not clear document expiry alerts.</p></Panel><Panel title="Lifecycle activity"><ActionHistory entries={vendor.history} /></Panel></div></div>
  </div>;
}
