import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { requisitionApi, procurementError } from "@/services/procurement";
import { useAuth } from "@/features/auth/use-auth";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ActionDialog, ActionHistory, Choice, Field, ItemSummary, PageHeading, Panel, QueryState } from "@/features/procurement/procurement-ui";
import { bdt, closingIso, date, label, tenderTypes } from "@/features/procurement/procurement-options";

export function RequisitionDetailPage() {
  const { id = "" } = useParams(); const { user } = useAuth(); const cache = useQueryClient(); const navigate = useNavigate();
  const [converting, setConverting] = useState(false); const [conversionError, setConversionError] = useState(""); const [type, setType] = useState("public_tender");
  const query = useQuery({ queryKey: ["requisitions", id], queryFn: ({ signal }) => requisitionApi.get(id, signal) });
  const action = useMutation({ mutationFn: ({ name, note }: { name: string; note: string }) => requisitionApi.action(Number(id), name, note), onSuccess: async () => { await Promise.all([cache.invalidateQueries({ queryKey: ["requisitions"] }), cache.invalidateQueries({ queryKey: ["dashboard"] })]); toast.success("Requisition updated."); } });
  if (query.isPending || query.isError) return <QueryState pending={query.isPending} error={query.error} retry={() => void query.refetch()} />;
  const record = query.data; const admin = user?.role === "admin"; const canReview = admin || user?.role === "approver";
  const act = (name: string) => async (note: string) => { await action.mutateAsync({ name, note }); };
  return <div className="space-y-6"><PageHeading title={record.title} description={`${record.requisition_number} · ${record.department}`} back="/admin/requisitions" action={<StatusBadge status={record.status} />} />
    <div className="flex flex-wrap gap-2">{admin && ["draft", "revision_required"].includes(record.status) && <><Button nativeButton={false} render={<Link to={`/admin/requisitions/${id}/edit`} />}>Edit requisition</Button><ActionDialog title="Submit for approval" description="Send this request to the hospital approval queue." pending={action.isPending} onConfirm={act("submit")} /></>}{canReview && record.status === "pending_approval" && <><ActionDialog title="Approve" description="Approve this hospital requisition for procurement." pending={action.isPending} onConfirm={act("approve")} /><ActionDialog title="Request revision" description="Return the request with clear revision instructions." needsNote pending={action.isPending} onConfirm={act("request_revision")} /><ActionDialog title="Reject" description="Reject this requisition and record the reason." needsNote destructive pending={action.isPending} onConfirm={act("reject")} /></>}{record.tender_id && <Button nativeButton={false} render={<Link to={`/admin/tenders/${record.tender_id}`} />}>Open linked tender</Button>}</div>
    <div className="grid gap-4 sm:grid-cols-3">{[["Estimated budget", bdt(record.estimated_budget)], ["Required date", date(record.required_date)], ["Requested by", record.requester]].map(([title, value]) => <Panel key={title} title={title}><p className="text-lg font-semibold text-primary">{value}</p></Panel>)}</div>
    <Tabs defaultValue="overview"><div className="overflow-x-auto pb-2"><TabsList>{["overview", "items", "approval_history", "activity"].map((tab) => <TabsTrigger key={tab} value={tab}>{label(tab)}</TabsTrigger>)}</TabsList></div><TabsContent value="overview"><Panel title="Clinical need & procurement scope"><p className="whitespace-pre-wrap leading-relaxed text-muted-foreground">{record.description || "No description recorded."}</p><p className="text-sm">Category: <strong>{label(record.category)}</strong></p><p className="rounded-lg bg-secondary p-3 text-xs text-muted-foreground">Approval route: Department request → Hospital approver → Procurement. This demo uses a single hospital approval step.</p></Panel></TabsContent><TabsContent value="items"><Panel title="Requested items"><ItemSummary items={record.items} /></Panel></TabsContent><TabsContent value="approval_history"><Panel title="Approval history"><ActionHistory entries={record.history?.filter((entry) => ["submit", "approve", "reject", "request_revision"].includes(entry.action)) ?? []} /></Panel></TabsContent><TabsContent value="activity"><Panel title="Requisition activity"><ActionHistory entries={record.history} /></Panel></TabsContent></Tabs>
    {admin && record.status === "approved" && <Panel title="Convert approved requisition to tender / RFQ"><p className="text-sm text-muted-foreground">Item specifications and quantities carry forward into the tender BOQ. Review eligibility before publishing.</p><form className="space-y-4" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setConverting(true); setConversionError(""); try { const tender = await requisitionApi.convert(record.id, { title: String(form.get("title")), type, closing_date: closingIso(String(form.get("closing_date"))) }); await Promise.all([cache.invalidateQueries({ queryKey: ["requisitions"] }), cache.invalidateQueries({ queryKey: ["tenders"] }), cache.invalidateQueries({ queryKey: ["dashboard"] })]); toast.success("Tender created from approved requisition."); navigate(`/admin/tenders/${tender.id}`); } catch (failure) { setConversionError(procurementError(failure)); } finally { setConverting(false); } }}><fieldset disabled={converting} className="grid gap-4 sm:grid-cols-3"><Field title="Tender title"><Input name="title" required maxLength={200} defaultValue={record.requisition_number === "PR-001" ? "ICU Equipment Supply 2026" : record.title} /></Field><Field title="Tender type"><Choice title="Tender type" value={type} onChange={setType} options={tenderTypes} /></Field><Field title="Closing date / time (Dhaka)"><Input name="closing_date" required type="datetime-local" /></Field></fieldset>{conversionError && <p role="alert" className="text-sm text-destructive">{conversionError}</p>}<Button type="submit" disabled={converting}>{converting ? "Converting…" : "Convert to tender"}</Button></form></Panel>}
  </div>;
}
